### ISSUE TITLE
Feature: List installed packages and update list

### ISSUE THREAD

**Issue by borsTiHD** [techno-express/node-sys#3]
Hi, this is an amazing project.
I want to use it in my small hobby project, but it miss a few features I would love to see.
Is there a chance you would add two more features?

First, I would like to have a way to get all the installed packages..
Currently I only use `apt list --installed`.
Output example:
```
[
    { name: 'package1', version: '1.0.0', state: 'upgradable' },
    { name: 'package2', version: '0.0.1', state: 'installed' },
]
```

Secondly, I would like to have a way to refresh the package list.
For this I currently use `apt-get update`.

--

Why I'm asking?
I'm building a small app for controlling a raspberry pi ([here](https://github.com/borsTiHD/pi-control)) and this would be an easier and better way to integrate a package manager.
Thanks in advanced.

**Comment by TheTechsTech** [comment]
This package use an simple method to check for installed packages, if it's not present by the command line, meaning not reachable in system path, it's not installed. 

This package not really querying the actual package manger, just installing package, it's still possible the package just might be actually already installed. 

You should sunmit each package manger's **list software** command options. I would then be able to add at least that feature. 

Anyway, Listing and updating software is totally outside the use case for using this package. This is a way to add host system packages for NPM package requirements by a script at **install time**.

**Comment by borsTiHD** [comment]
Ok, seems logic.
Thanks for your time to answer my request and keep it up. :)
